# Primary patterns for main addresses
[ZoneAddr]
Start=0x19F000
Pattern=\x41\xB8\x20\x00\x00\x00\x48\x8D\x15\x7E\x46\x73\x00\x48\x8D\x0D\x1F\x21\xD1\x00\xE8\xD6\x74\x40\x00
Mask=xxxxxxxxx????xxrttttx????

[SpawnHeaderAddr]
Start=0xB7000
Pattern=\x40\x53\x48\x83\xEC\x20\x48\x8B\xDA\x8B\x51\x10\x48\x8B\x0D\xF5\x04\xE7\x00\x48\x8B\x01\xFF\x50\x10
Mask=xxxxxxxxxxxxxxrttttxxxxxx

[CharInfo]
Start=0xD3000
Pattern=\x40\x53\x48\x83\xEC\x20\x48\x8B\xD9\x48\x8B\x0D\xA8\x60\xDD\x00\x48\x85\xC9\x74\x2C
Mask=xxxxxxxxxxxrttttxxxx?

[ItemsAddr]
Start=0x228000
Pattern=\x48\x8D\x0D\xFD\xFB\xC7\x00\xE8\xA0\x62\x4B\x00\x48\x8D\x05\xE9\xFB\xC7\x00\x48\x83\xC4\x28\xC3
Mask=xxx????x????xxrttttxxxxx

[TargetAddr]
Start=0xEF000
Pattern=\x48\x8B\x15\x74\x95\xDB\x00\x48\x3B\x15\x0D\xD1\xCE\x00\x0F\x84\x91\x02\x00\x00\x48\x85\xD2
Mask=xxx????xxrttttxx????xxx

[WorldAddr]
Start=0x284000
Pattern=\x8B\x15\xBE\xC5\xC2\x00\x48\x8B\x0D\xD3\x40\xC2\x00\xE9\x6E\x2D\x42\x00
Mask=xx????xxrttttx????

# Secondary patterns for offsets that are not found with the primary pattern
[SpawnInfoNextOffset]
Start=
Pattern=
Mask=

[SpawnInfoPrevOffset]
Start=
Pattern=
Mask=

[SpawnInfoLastnameOffset]
Start=
Pattern=
Mask=

[SpawnInfoXOffset]
Start=
Pattern=
Mask=

[SpawnInfoYOffset]
Start=
Pattern=
Mask=

[SpawnInfoZOffset]
Start=
Pattern=
Mask=

[SpawnInfoSpeedOffset]
Start=
Pattern=
Mask=

[SpawnInfoHeadingOffset]
Start=
Pattern=
Mask=

[SpawnInfoNameOffset]
Start=
Pattern=
Mask=

[SpawnInfoTypeOffset]
Start=0xD9400
Pattern=\x49\x8B\x46\x10\x80\xB8\x35\x01\x00\x00\x00\x75\x3C
Mask=?x?xxxttttxx?

[SpawnInfoSpawnIDOffset]
Start=0xA5400
Pattern=\x45\x84\xFF\x75\x67\x8B\x90\x68\x01\x00\x00\x48\x8B\x0D
Mask=xxx??xxttttxxx

[SpawnInfoOwnerIDOffset]
Start=
Pattern=
Mask=

[SpawnInfoHideOffset]
Start=
Pattern=
Mask=

[SpawnInfoLevelOffset]
Start=0xD5400
Pattern=\x0F\xB6\x54\x11\x48\x88\x90\xFD\x03\x00\x00\x48\x8B\x8E\x00\x00\x00\x00
Mask=xxxxxxxttttxxx????

[SpawnInfoRaceOffset]
Start=0x18A400
Pattern=\x41\xB8\xA0\x0F\x00\x00\x40\x88\xAB\xF4\x0F\x00\x00\x48\x89\xAB\x00\x00\x00\x00
Mask=xxxxxxxxxttttxxx????

[SpawnInfoClassOffset]
Start=0x9D400
Pattern=\x89\x44\x24\x34\x8B\x83\xFC\x0F\x00\x00\x89\x44\x24\x38\x0F\xB6\x83\x00\x00\x00\x00
Mask=xxxxxxttttxxxxxxx????

[SpawnInfoPrimaryOffset]
Start=0xD5400
Pattern=\x89\xB7\xA8\x1E\x00\x00\x0F\x11\x87\x04\x11\x00\x00\x89\xB7\x00\x00\x00\x00
Mask=xxxxxxxxxttttxx????

[SpawnInfoOffhandOffset]
Start=0xD5400
Pattern=\x89\xB7\xBC\x1E\x00\x00\x0F\x11\x87\x18\x11\x00\x00\x89\xB7\x00\x00\x00\x00
Mask=xxxxxxxxxttttxx????